image_height: 64
image_width: 64
num_classes: 200
num_training: 100000
num_val: 10000
batch_size: 32
epochs: 500
train_dir:  "gs://tinyimage_net/train"
validation_dir:  "gs://tinyimage_net/validation"
model_name: "TinyImageNetModel"